######################################################################
# Automatically generated by qmake (1.07a) Wed Dec 28 19:13:33 2016
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += test.h
SOURCES += test.cpp
