
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 
"

"runtime! vimrc_example.vim

" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
"
"
"

syntax on
set expandtab
filetype plugin indent on
set nu
set mouse=a
set wildmenu
set ai
set tabstop=2
set softtabstop=2
set shiftwidth=2
colorscheme ron

